"""empty message

Revision ID: 89298b51e10a
Revises: 0392798685a4
Create Date: 2020-07-26 19:07:00.557243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89298b51e10a'
down_revision = '0392798685a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pname', sa.String(length=100), nullable=False),
    sa.Column('pdatetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    # ### end Alembic commands ###
